
countries = [
     "AFRIQUE DU SUD","ALGERIE","ALLEMAGNE","ARABIE SAOUDITE","AUSTRALIE",
  "AUTRICHE","BELGIQUE","BENIN","BURKINA FASO","CAMEROUN","CANADA",
  "CHINE","REPUBLIQUE DU CONGO","COREE DU SUD","COTE D'IVOIRE","CUBA","DANEMARK",
  "EGYPTE","ESPAGNE","ETATS-UNIS","FRANCE","GABON","GHANA","HAITI","HONG-KONG","INDE","INDONESIE","ISRAEL",
  "ITALIE","JAPON","KENYA","MADAGASCAR","MALI","MAROC","NIGER","NIGERIA","NORVEGE","NOUVELLE-ZELANDE",
  "PAYS-BAS","QUATAR","ROYAUME-UNI","RUSSIE","RWANDA","SENEGAL","SINGAPOUR","SUEDE","SUISSE","TAIWAN","TOGO",
  "TUNISIE","TURQUIE",
]